services:
  api:
    container_name: VizionerAPI
    build:
      context: .
      dockerfile: api/Dockerfile
    image: vizioner-api
    volumes:
      - ./models:/models:ro
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - tasker

  worker:
    container_name: VizionerWorker
    build:
      context: .
      dockerfile: worker/Dockerfile
    image: vizioner-worker
    volumes:
      - ./models:/models:ro
    env_file:
      - ./.env
    depends_on:
      - tasker

  tasker:
    container_name: VizionerMemory
    image: redis:7.4-alpine
    ports:
      - "6379:6379"

  content:
    container_name: VizionerStorage
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    env_file:
      - ./.env
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - content-data:/data

volumes:
  content-data:
